version: '3'

services:
  mysqldb:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: stasek123
      MYSQL_DATABASE: stas_db
    ports:
      - "3308:3306"
    security_opt:
      - seccomp:unconfined

#  python_app:
#    build: .
#    depends_on:
#      - "mysqldb"
#    ports:
#      - "50000:50000"
#


